# Generated by Django 5.2 on 2025-06-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
