# Generated by Django 5.2 on 2025-06-27 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What did you spend on?', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='How much did you spend?', max_digits=8)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Stationery', 'Stationery'), ('Mobile Recharge', 'Mobile Recharge'), ('Entertainment', 'Entertainment'), ('Hostel', 'Hostel'), ('Other', 'Other')], max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='Optional note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
