# Generated by Django 5.2 on 2025-05-30 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('agenda', models.TextField()),
                ('DatenTime', models.DateTimeField(auto_now_add=True)),
                ('meeting_time', models.DateTimeField()),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Employee.employee')),
            ],
        ),
    ]
