# Generated by Django 5.2 on 2025-05-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='member',
        ),
        migrations.AddField(
            model_name='meeting',
            name='member',
            field=models.ManyToManyField(to='Employee.employee'),
        ),
    ]
