# Generated by Django 5.2 on 2025-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ammounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectaccounts',
            name='Projectname',
            field=models.CharField(max_length=20),
        ),
    ]
