# Generated by Django 5.2 on 2025-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=300)),
                ('staff', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
