# Generated by Django 5.2 on 2025-05-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='desp',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='finishdatetime',
            field=models.DateTimeField(auto_now_add=True, default="2025-02-25 23:26:11"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='payment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='paymentreceive',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='projectdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
