# Generated by Django 5.2 on 2025-05-09 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectmodel_desp_projectmodel_finishdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='finishdatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
