# Generated by Django 5.2 on 2025-05-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_projectmodel_finishdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='desp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='finishdatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
