# Generated by Django 5.2 on 2025-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectmodel_finishdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='finishdatetime',
            field=models.DateTimeField(default="2025-02-25 23:26:11"),
        ),
    ]
