# Generated by Django 5.2 on 2025-05-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectmodel_finishdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='desp',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='finishdatetime',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='paymentreceive',
        ),
    ]
