# Generated by Django 5.2 on 2025-05-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_projectmodel_desp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcat', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='cat',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='desp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='finishdatetime',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-25 23:26:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='payment',
            field=models.IntegerField(default=1212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='paymentreceive',
            field=models.FloatField(default=1.2),
            preserve_default=False,
        ),
    ]
