# Generated by Django 5.2 on 2025-05-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectcategory_remove_projectmodel_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.projectcategory'),
        ),
    ]
